### ISSUE TITLE
Covid19 Mode

### ISSUE THREAD

**Issue by getjump** [egregors/vldc-bot#101]
So, i think we should respect Covid19, by implementing some features in our chat!

Commands:
```/cough``` - One, who is already infected has an ability to infect someone with probability of 30%, if one doesn't wear a mask (on avatar), otherwise 1% (we kinda can detect type of mask, but we are doing this for fun...)
```/cvtest``` - Admin of chat, can perform a coronavirus test, results of a test are printed in chat
```/quarantine``` - Put a guy to quarantine for some amount of minutes (/mute, also we can allow a poor guy to post STICKERS!)
```/cvinfect``` - Admin can infect someone with probability 100%
```/cvstart``` - Doest start/reset CV mode, every day 1% of chat population is getting infected by CV, when someone infected reply to message, nor just posting previous and next message poster has a possibility to get infected, with probability 15%, unless "he was wearing a mask" - his avatar has a mask, then it is 1%
```/cvstop``` - Stops CV mode, unbans everyone who was banned by this mode
```/temp``` - Admin can measure a temperature of a guy, or he can do it by himself, infected has a higher temperature than a non infected, but this also could be common flu, also we should respect incubation period

Also, we can implement random coughing, like: infected people has a probability of 10% to cough in a minute, and non infected people like 0.2%.

Something like "lethality" could be good, too, we can do it like muting someone unless CV mode ends, lethality rate kind of 3% can do, or maybe ```1 / exp(1 / (lethality * days_since_infection))```

So, we can use the following dataset for mask detection https://www.kaggle.com/vtech6/medical-masks-dataset in attachment, you can find actual modified version of dataset where:
good - someone wearing a mask, tg_vldc - avatars with masks from our chat, int - different stuff from internet
none - no one is wearing a mask, faces - FLW faces

@C-Pro said he can learn NN to do this, also he shared a link https://github.com/zamhown/wear-a-mask -- we can implement something like ```/maskon``` so bot downloads user avatar and put mask on

There is a functionality that can help with this https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.jobqueue.html

**Comment by getjump** [comment]
/cough - works, need to confirm
/cvtest - works
/quarantine - probably broken, especially restriction in chat
/cvstart - works, but doesnt clear db via /cvstop handler need to fix
/temp - works, but probably can be done better

> Also, we can implement random coughing, like: infected people has a probability of 10% to cough in a minute, and non infected people like 0.2%.
 - works, need to confirm

> Something like "lethality" could be good, too, we can do it like muting someone unless CV mode ends, lethality rate kind of 3% can do, or maybe 1 / exp(1 / (lethality * days_since_infection))
- need to code

When restarting bot, job queue intervals seems like not working for random coughing and infection

**Comment by egregors** [comment]
*cough*
