### ISSUE TITLE
Add since-mode

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#11]
`since-mode` is counting and showing numbers of days since last mentation of _our favorite_ themes. 

It may be two option probably: catch themes buzz words in the messages, or use `/since_` command.

For example:

```
user: ну вообще, ООП решает эту проблему
vldc_bot: This is are 0 days since ООП discussion
```

or

```
user: современный php – не такой плохой язык, им вполне можно пользоваться
user2: /since_php
vldc_bot: This is are 2 days since Современный ПеХеПе discussion
```

For these two options, we need the preselected list of _our favorite_ themes.
Alternativly, we may allow users creating they owns since-words, like:

```
user: да макось вообще не позволяет ничего кастомизировать, толи дело арч
user2: /since бест ОС евер
vldc_bot: This is are 0 days since бест ОС евер discussion
```

В таком случае можно добавить вывод всех since за все время: 
```
user: /since_all
vldc_bot:
ООП: 0 days
Современный ПеХеПе: 20 days
бест ОС евер: 2 days
```

Obviously, we need some persistent storage for this kind of stuff. Let's say it will be mongo

- [x] add skill
- [x] add adapter for persistent storage
  - [x] add compose to run bot + storage
  - [x] add .env file for configuration compose (token, chat name, mongo stuff)
  - [x] add mongo into compose (everything become better with mongo)
  - [x] add mongo driver to requirements
  - [x] some way to backups? neh 
- [x] update docs | readme | cmd info in the come skill
- [x] since cmd
- [x] since_all cmd

**Comment by C-Pro** [comment]
stateless but with persistent storage? what do you mean?

**Comment by egregors** [comment]
I mean, I don't wanna store any state in the bot container \ instance. At this case, I believe we may use something like [Cloud Firestore](https://firebase.google.com/pricing) Do we love Google, hah?

**Comment by C-Pro** [comment]
We totally can, but I do not think we shoud. It would be way easier to fire up mongo alongside bot instance via docker-compost
We do not need firebase features like scalability, offline syncronization, realtime updates, network hiccups, occasional unexpected money spending or quota-reaching :)

**Comment by egregors** [comment]
Make sense. I'll change the issue description.
