### ISSUE TITLE
Remove all voice messages from the chat. Or recognize it and replace original message by text 

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#130]
Maybe, as a bonus – ban voice message sender for a few hours. 

- [x] catch voice messages
- [x] remove voice messages
  - [x] try to recognize it and replace by text
- [x] mute sender for few hours

It will be `nastya-mode`. Don't ask. Just don't ask 🙅

**Comment by egregors** [comment]
@C-Pro waiting for your help!

**Comment by AlexanderSutul** [comment]
Hi! I can implement logic to make it work using google cloud. But who will pay for it? Do you know any alternative api to recognize voice?

**Comment by AlexanderSutul** [comment]
Let me know if you find any alternative for voice recognition. My tg is @al_web.

**Comment by egregors** [comment]
@AlexanderSutul looks like our requirements nicely fit the free limits. You could use your credentials with free limits for dev and debug. In the production, we'll run voice recognition with our credentials. That's right, @C-Pro ?

**Comment by C-Pro** [comment]
Yep

**Comment by egregors** [comment]
rel #140

**Comment by egregors** [comment]
@C-Pro could you please check a dev bot environment? Let's test it before putting feature into master.
We need to update ENV for production as well

**Comment by C-Pro** [comment]
I do not see any changes in env here
