### ISSUE TITLE
Add russian translation for bots messages

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#16]
Need to duplicate all bots messages in two languages. For some reasons, someone from the chat believes it will be a good option for a chat in Russian, idk. And, maybe new users will read bots messages more carefully.

**Comment by C-Pro** [comment]
Maybe we can come up with some compromise option? Like chat in esperanto, or haskell?

**Comment by Grawl** [comment]
we all write in russian there

**Comment by Grawl** [comment]
Telegram API allows to replace message text and buttons in-place.

We can add second button to welcoming message and place a flag of Great Britain (or USA) on it. this button will replace russian welcoming text with translated.

**Comment by egregors** [comment]
Done
