### ISSUE TITLE
Get version from `pyproject` directly

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#169]
- [x] parse `pyproject.toml`
- [x] update `_version` func to get version as a string
- [x] remove `__version__` from `skills.__init__.py`  

toml: https://github.com/uiri/toml

**Comment by AlexanderSutul** [comment]
I'll do it.

**Comment by AlexanderSutul** [comment]
@egregors  check please #170

**Comment by egregors** [comment]
@AlexanderSutul looks great! 🔥 🔥 🔥  Please, check a little change request out. #170
