### ISSUE TITLE
VLDC Code of Conduct

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#17]
@C-Pro I believe you know much more about this.

- [ ] main points
  - [ ] ru
  - [ ] en
- [ ] md
- [ ] raw txt for posting CoC by bot on demand (or I may just post the link to GitHub page with CoC)

**Comment by C-Pro** [comment]
I think we can share it with GDG Vladivostok:

https://devfest.gdgvl.ru/code-of-conduct/

##  Markdown source en/ru: 
https://github.com/C-Pro/site-devfest-2019/blob/master/content/code-of-conduct.md
https://github.com/C-Pro/site-devfest-2019/blob/master/content/code-of-conduct.ru.md

**Comment by C-Pro** [comment]
But I think we should have short one for the bot with a link to fullsize COC EULA  MEGA PRO XXL MAX

**Comment by Grawl** [comment]
GDG COC is good enough

**Comment by egregors** [comment]
Any progress?
