### ISSUE TITLE
Post in the chat message with the current version when Nyan is updating

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#222]
Because we haven't any CI indication of how successful the last deployment was, let's Nyan will say it by himself!

Smth like: 
```
Nyan: А вот и новая версия меня! 0.7.12
```

The message should be deleted after a while

UPD: looks like little update of `backdoor` will be enough

- [x] Add `sync` mode into `Backdoor`: https://github.com/vldc-hq/backdoor/pull/3
- [x] Update `nayn_bot.yml` (set `--max-time` to `curl` call)
- [x] Test it!

**Comment by egregors** [comment]
@C-Pro You think so? I mean, we do not know what happening when GitHub Action trigger the `backdoor`. Was deploy successful or not. How could we be sure?

Looks like sending a sort message exactly in bot boot time is a pretty explicit way, isn't it?

Or could you provide a more suitable way to solve it?

**Comment by C-Pro** [comment]
Backdoor can wait for deploy and return http 200/50x error code depending if deploy commend returns zero or smth else.

**Comment by egregors** [comment]
@C-Pro check this out, when u got a time: https://github.com/vldc-hq/backdoor/pull/3
