### ISSUE TITLE
Collect all date from all users in the chat to find out who is the bot

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#3]
- [ ] collect all logs
- [ ] map it with users
- [ ] find the bots
- [ ] find the flooders 🍭

**Comment by Grawl** [comment]
> all date

all data?

**Comment by Grawl** [comment]
to find the flooders we have a lot of other bots

**Comment by egregors** [comment]
Agree. But else I wanna make `/markov` command to generate random vldc-like strings by Markov Chains. Mostly this is the true cause to collect all log :D But for finding bots, you right, we should use another tool

**Comment by Grawl** [comment]
Generate random phrases with Markov chains is cool idea!

**Comment by egregors** [comment]
wont
