### ISSUE TITLE
Add mute command

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#34]
Something like `/mute @C-Pro 90` for muting (removing all messages) by user @C-Pro during 90 minutes

**Comment by getjump** [comment]
Implementing this, actually there are a telegram feature you can restrict user from messaging in group.

So /mute @username or reply /mute (+ delete source message optionally) for default period of time or extended version, aka /mute @username period or reply /mute period

No need to use internal db in that case, telegram permissions should do

**Comment by egregors** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/blob/32dd415fb86e822a977fbdf2e4b78f945715eb57/telegram/bot.py#L2689

**Comment by getjump** [comment]
There will be a slight overhead, since we need one extra request to get user_id from mention, actually we can build a dictionary username -> user_id, and keep it fresh with updates but dunno, that is another issue probably

**Comment by getjump** [comment]
Well, version like /mute @username will not work in that case, since we need user_id and it is actually not possible in current API

**Comment by egregors** [comment]
So, as we learned today, our group is a supergroup

**Comment by egregors** [comment]
Current implementation required a reply by admin for an abusive message with command `/mute n` where `n` is the number of mute minutes.
