### ISSUE TITLE
Add CI for new versions

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#39]
@C-Pro could you add some automation for deployment each new version?

After each push into master Docker Hub will build the new latest version on the container. And, looks like we may just pull new container, but sometimes we are updating the docker-compose (for adding new services for example), and at this case, we need more smartest deploy.

We may user GitHub Actions for this purpose, I guess. So, I believe it may look like:
- [x] push to master -> check (stylelints, tests, mypy, etc)
- [x] DokcerHub build new Image (wait for it)
- [x] if checks are the green and new image is ready: deploy a new version:
 
@lamak now it is your horse 🐴

**Comment by egregors** [comment]
@C-Pro now all new versions from master become an [image](https://github.com/egregors/vldc-bot/packages/53908) with tag `latest` and goes to GitHub docker registry. Check out `Packages`

So, we may remove the sleep step in the CI now

**Comment by C-Pro** [comment]
done

**Comment by egregors** [comment]
NIce one!
