### ISSUE TITLE
Add quick bot-checker for new members

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#4]
- [x] Detect new users in the chat 
- [x] Send the message with a mention for each new user and ask for a replay 
- [x] Wait for the answer
- [x] Ban user if bot will not get a reply
- [ ] Post some funny stuff
- [x] Post a message with a ban confirming

Plus:
- [x] move all globals into `config`
- [x] refactoring
- [x] move filters to external file
- [x] update readme (put more vldc stuff)
- [x] rename repo to vldc_bot
- [x] replace `smile_bot` by `vldc_bot` in the VLDC chat

The main problem right meaw than once kicked user can't retry to join the chat.

**Comment by aleksandrbazhin** [comment]
That way it won't work. From https://core.telegram.org/bots:
"Bots can't initiate conversations with users. A user must either add them to a group or send them a message first."
Looks like the greeting "towel" questions have to be public.

**Comment by egregors** [comment]
> "Bots can't initiate conversations with users. A user must either add them to a group or send them a message first."

@aleksandrbazhin all this mostly about initiate a conversation with a bot. Telegram prohibit bots to send messages to users if they haven't any connections (the random bot can't mention you if you do not add him into your group or text him first)

In our case, we already have the bot in the group and had granted  him admin permissions

API supports mentions, btw: https://core.telegram.org/bots/api#messageentity

**Comment by aleksandrbazhin** [comment]
Sorry, thought about private message, not personal mention.

**Comment by egregors** [comment]
I updated the description to avoid ambiguity

**Comment by Grawl** [comment]
towel is better

**Comment by egregors** [comment]
@Grawl offer us a good GIF, or sticker

**Comment by aleksandrbazhin** [comment]
Since I got the notification, suggesting Towelie from https://t.me/addstickers/southpack

**Comment by Grawl** [comment]
not this Towelie

**Comment by egregors** [comment]
good enough
