### ISSUE TITLE
Replace all "..." by 🤔

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#46]

**Comment by Grawl** [comment]
?

**Comment by egregors** [comment]
Still do not sure, does bot have perm for editing user messages

**Comment by Grawl** [comment]
why we want it?

**Comment by egregors** [comment]
To ironically reduce ellipsis abuse

**Comment by Grawl** [comment]
ok but think about code samples such as

```js
const foo = (...bar) => console.log(bar)
```

**Comment by egregors** [comment]
Hm, you're right, nice point. I'll think about this. However, until I don't know, is it even possible to edit users messages by bot according to API, this issue is kind of `wontfix`

**Comment by Grawl** [comment]
I respect this `wontfix` tag because I think bot should not edit user messages

**Comment by egregors** [comment]
wont
