### ISSUE TITLE
Remove the original /still message

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#56]
Remove original `/still smth` message after bot posted answer

**Comment by zemlya25** [comment]
вот бы только в try обернуть удаление, а вывод сообщения в finaly или else (не знаю куда оптимальней даже)
была мысль прикорячить декоратор для команд, удаляющих оригинал сообщения

**Comment by egregors** [comment]
feel free to PR

**Comment by egregors** [comment]
Solved at #76
