### ISSUE TITLE
Rework "uwu" for catching all uwu-stuff automatically (not only a command)

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#78]
Need to replace `CommandHandler` by `MessageHandler` and catch all "uwu-like" strings.

- [x] remove cmd `/uwu`
- [x] collect all posible variants of `uwu`
- [x] check every message for uwu-like entry and post the image if it nessessery

smth like this:
```
u1: а вы слышали про язык Rust? Это просто UwwwwwU
bot: *replay for u1 message* DON'T UWU, U1! -> *dontuwu_img*
```

**Comment by Grawl** [comment]
`/uw+u/gmi` https://regex101.com/r/O1HqrE/1

**Comment by Grawl** [comment]
what if some word contains `uwu` but it's not an UwU

**Comment by egregors** [comment]
@Grawl what about `UvvU`?

**Comment by Grawl** [comment]
looks like uwu

**Comment by egregors** [comment]
rel #87

**Comment by egregors** [comment]
thanks @aggyomfg 🔥
