### ISSUE TITLE
Add shortcuts for most common commands via BotFather 

### ISSUE THREAD

**Issue by surenkov** [egregors/vldc-bot#84]
@egregors, 
I think it can be useful to list some (or all) Nyan commands when user is typing `/`, like here:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/942909/70629924-6f76d980-1c76-11ea-8a33-def87fa7ca70.png">

It can be done via BotFather, with `/setcommands` to be precise: https://core.telegram.org/bots#botfather-commands

**Comment by egregors** [comment]
Agree, I gonna make it during the readme updating

**Comment by egregors** [comment]
rel #45

**Comment by egregors** [comment]
Done already
