### ISSUE TITLE
📊 Store roll stats persistently

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#92]
- [x] collection for hussars
- [x] document for hussar
- [x] store and API for hussar CRUD
- [x] update `roll` skill to store stats
- [x] base roll stats
- [ ] read-only API for `roll` stats processing
- [ ] tests :\
- [ ] documentation :\ :\ :\ :\
- [x] hussars leader board
- [x] mobile friendly hussars leader board

**Comment by egregors** [comment]
rel #91 #89

**Comment by egregors** [comment]
```
2020-03-04 11:26:59,297 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/python_telegram_bot-12.0.0b1-py3.7.egg/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/app/bot/mode.py", line 170, in cleanup_wrapper
    result = func(*args, **kwargs)
  File "/app/bot/skills/roll.py", line 163, in show_hussars
    board += f"{str(timedelta(seconds=(h['total_time_in_club']))).ljust(17)} " \
KeyError: 'username'
```

**Comment by AlexanderSutul** [comment]
`mobile friendly hussars leader board`
How about to convert a table to an image?

**Comment by egregors** [comment]
> `mobile friendly hussars leader board`
> How about to convert a table to an image?

@AlexanderSutul  Sounds good! Will you take it?

**Comment by AlexanderSutul** [comment]
> > `mobile friendly hussars leader board`
> > How about to convert a table to an image?
> 
> @AlexanderSutul Sounds good! Will you take it?

Yep.

**Comment by AlexanderSutul** [comment]
[#149 ](https://github.com/egregors/vldc-bot/pull/149)

**Comment by egregors** [comment]
Let's say it's done for now
